services:
  postgresdb:
    image: postgres:latest
    container_name: OnlineQuestionnaire_postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "1235:5432"
    networks:
      - OnlineQuestionnaire
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 10

  app:
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: OnlineQuestionnaire-app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}

    ports:
      - 8080:8080
      - 40000:40000
    volumes:
      - .:/app
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - OnlineQuestionnaire

  redisdb:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - OnlineQuestionnaire

volumes:
  pg_data:
  redis_data:

networks:
  OnlineQuestionnaire:
    driver: bridge