app_name: OnlineQuestionnaire
debug: true
server:
  host: localhost
  port: 8080
DB:
  user: root
  password: root
  dbname: OnlineQuestionnaire
  host: localhost
  port: 5432
  sslmode: disable
jwt:
  secret: ""
  expiration: 5 #minutes
logging:
  level: DEBUG
  filename: /tmp/application.log
  maxsize: 10 # MB
  maxbackups: 10
  maxage: 30
  compress: true





