app_name: OnlineQuestionnaire
debug: true
server:
  host: localhost
  port: 8080
DB:
  user: root
  password: root
  dbname: OnlineQuestionnaire
  host: localhost
  port: 5432
  sslmode: disable






