app_name: OnlineQuestionnaire
debug: true
server:
  host: localhost
  port: 8080
DB:
  user: admin
  password: admin123
  dbname: questionnaire
  host: localhost
  port: 5432
  sslmode: disable


jwt:
  secret: ""
  expiration: 5 #minutes







